### ISSUE TITLE
Which skill counts for Mortal Blow / Armor Piercing?

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#11]
1. Which skills increase count of Mortal Blow, and reduce cooltime of Armor Piercing?
2. Which skills are buffed by Mortal Blow / Armor Piercing?

I think Storm Arrow and Wind of Pray only counts for it, but need to check V skills

**Comment by Monolith11** [comment]
Mortal Blow and Armor Piercing is currently applied on direct attack skills in my sheet.
I didn't test V skills.

**Comment by icepeng** [comment]
![vvvvv](https://user-images.githubusercontent.com/12782606/90351706-ff79e800-e07b-11ea-9f5d-865895bd41c7.gif)

Guided Arrow increases Mortal Blow stack

**Comment by icepeng** [comment]
https://github.com/oleneyl/maplestory_dpm_calc/issues/247

Collecting test results here

**Comment by icepeng** [comment]
#18
