### ISSUE TITLE
Marksman's Freezer can hit in 400 distance

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#12]
My marksman friend >260 level said freezer cat hit at 400

Will check video later

**Comment by Monolith11** [comment]
3211005.summon.info.range.lt.x is -280 so I made it 280 range.
Maybe I didn't test.

**Comment by icepeng** [comment]
If a character attacks at a distance of 400, the freezer does not attack.

However, if you attack within 280 range, the freezer will start attacking. After the freezer starts attacking, the freezer continues to attack even if the distance is 400.

**Comment by Monolith11** [comment]
That makes sense.
So in actual fight, Marksmans sometime goes 280 or below range then Freezers will start attack.
I'm gonna make Freezers will attack.
