### ISSUE TITLE
Kain Check

### ISSUE THREAD

**Issue by Monolith11** [Monolith11/memo#122]
- [x] 발현 skill can generate gauge or not
- [x] 발현 cooldown is affected by cdr or not
- [x] Dragon Fang's attack interval
- [x] Scattering Shot gauge gain when multiple hit
- [x] Remain Incense count is different per skill
- [x] Falling Dust jump delay
- [x] Shaft Break(Tornado) duration and attack interval
- [x] Poison Needle duration and attack interval
- [x] Grip of Agony attack interval
- [x] Chasing Shot's multiple hit can generate gauge or not
- [x] Sneaky Sniping's multiple hit can generate gauge or not
- [x] Sneaky Sniping can end keydown without passes prepare.time or not
- [x] Sneaky Sniping count cooldown while keydown or not
- [x] Poison Needle count cooldown while keydown or not
- [x] Dragon Burst's multiple hit can generate gauge or not
- [x] Dragon Burst count cooldown while keydown or not
- [x] Fatal Blitz count cooldown while keydown or not
- [x] Death Blessing buff uptime

**Comment by icepeng** [comment]
* 발현 skil cannot generate gauge
* 발현 cooldown is not affected by cdr
* Dragon Fang's attack interval is near (1650 * 7 + 3000) / 7
  * 1650ms between attack, and 3000ms between attack mode
* Scattering Shot only gain gauge once
* Remain Incense Count
  * StrikeArrow 1
  * ScatteringShot 2, but in most case, there are some time gap between missiles hit, so 2*2 is observed
  * ShaftBreak 6
  * Falling Dust 8
  * SneakySniping 8
  * DragonBurst 1 per tick
  * ThantosDescent(End) 2 per activation (9 activation)
* ShaftBreak(Tornado) activation is 12 times, so total 3*12 hit
* Poison Needle(spin) activation is 4 times, so 8*4 hit
* GripOfAgony attack interval is 330~340ms, 58 activation, total 58*6 hit
* Chasing Shot generate gauge only once
* Sneake Sniping generate gauge only once
* DragonBurst generate gauge only once... or does not generate gauge? need check
* DragonBurst cooltime starts with keydown
* FatalBlitz too
