### ISSUE TITLE
About Bow Master's Quiver Fullburst Crit Damage%

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#13]
Bow Master gains 8% more Critical Damage if Poison Arrow is applied to an enemy.

While Quiver Fullburst is active, Poison Arrow is applied to an enemy, so crit damage% should be applied.

I can't find a cell related to this in your sheet, so please check.

**Comment by Monolith11** [comment]
It's calculated at H183.

**Comment by icepeng** [comment]
Confirmed. Thank you.
