### ISSUE TITLE
Paladin Lightning Charge DoT Damage is missing

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#16]
Lightning Charge has "기절하지 않는 적은 115% 지속 데미지" option which means "115% DoT damage for not stunned enemy"

**Comment by Monolith11** [comment]
Thanks. Fixed.

**Comment by icepeng** [comment]
@Monolith11 I'm not sure about

Proc -> Stunnable -> Stun
             Not Stunnable -> DoT

Stunnable -> Proc -> Stun
Not Stunnable -> Dot

**Comment by Monolith11** [comment]
I'm not sure about that too so need to test.

**Comment by Monolith11** [comment]
#89
