### ISSUE TITLE
Illium's Magic Missile core enhancement is missing

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#27]
400004555.psdSkill has 152120016, and this skill code is Magic Missile.

But in sheet, Magic Missile's Final Damage is 1.

However, I have no idea with 152120017 skill. What is this?

**Comment by Monolith11** [comment]
can confirm. fixed.

152120017 is part of Glory Wing: Harmony Wing Beat
while 152120008 applies Bless Mark to ally, 152120017 applies Debuff Mark on enemies.
152120017.mobCount is 2+d(x/3) so 12 mob count
https://namu.wiki/w/%EC%9D%BC%EB%A6%AC%EC%9B%80/%EC%8A%A4%ED%82%AC#s-6.7

**Comment by icepeng** [comment]
Ahh I forgot about Harmony Wing Beat. Thank you.
