### ISSUE TITLE
Illium's Gram Holder final damage

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#29]
공격 준비 중 크리스탈 차지가 3 이상 충전되거나 글로리 윙 상태라면 최종 데미지 2배로 증가

Crystal Charge+3 or Glory Wing -> final damage +100%

In normal mode, Gram Holder's final damage is not enabled during Crystal Ignition. Because it is keydown skill, Crystal Charge does not increase.

In Glory Wing mode, Gram Holder is always final damage +100%.

**Comment by Monolith11** [comment]
can confirm. fixed.
