### ISSUE TITLE
Evan I30 cell is wrong

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#47]
Wrong
`=70+2*(30+$I$9+$I$10)+(80+(20+$I$9+$I$10))*ROUNDDOWN(J30/5,0)`

Right
`=70+2*(20+$I$9+$I$10)+(80+(20+$I$9+$I$10))*ROUNDDOWN(J30/5,0)`

Its master level is 20.

**Comment by Monolith11** [comment]
ty fixed
