### ISSUE TITLE
V skills that not confirmed whether attack speed is applied

### ISSUE THREAD

**Issue by Monolith11** [Monolith11/memo#50]
Skills not on this list have been confirmed, but I don't know if they have changed.
Basically attack speed is not applied to the start delay of the keydown skill. (Chain Arts: Tough Hustle is a only exception. I guess it's because it doesn't have prepare.time)
Basically attack speed is not applied to the end delay of the keydown skill, but it may be applied if that linked to another skill (tagged as finish) at the end, so need to check it.

all skills are confirmed

**Comment by icepeng** [comment]
Evan Spiral of Mana not applied

**Comment by Nougaga** [comment]
- [ ] Hero | Sword Illusion
- [ ] Paladin | Mighty Mjolnir
- [ ] Dark Knight | Beholder Impact
- [ ] Dark Knight | Darkness Aura
- [ ] Fire/Poison | Fury of Ifrit
- [ ] Fire/Poison | Poison Chain
- [ ] Ice/Lightning | Jupiter Thunder
- [ ] Crossbow Master | Repeating Crossbow Cartridge
- [ ] Crossbow Master | Full Burst Shot
- [ ] Pathfinder | Relic Unbound
- [ ] Night Lord | Throw Blasting
- [ ] Viper | Howling Fist (finish)
- [ ] Cannon | Pool Maker
- [ ] Soul Master | Celestial Dance
- [ ] Soul Master | Elysion
- [ ] Soul Master | Soul Eclipse
- [ ] Soul Master | Soluna Divide
- [ ] Flame Wizard | Blazing Orbital Flame
- [ ] Flame Wizard | Flame Discharge
- [ ] Flame Wizard | Salamander Mischief
- [ ] Wind Shooter | Vortex Sphere
- [ ] Night Walker | Rapid Throw (finish)
- [ ] Striker | Spear Lightning Continuity Attack
- [ ] Mihile | Light of Courage
- [ ] Mihile | Light of Courage (finish)
- [ ] Aran | Blizzard Tempest
- [ ] Luminous | Revelation Orb
- [ ] Mercedes | Royal Knights
- [ ] Phantom | Rift Break (move)
- [ ] Phantom | Rift Break (no-move)
- [ ] Eunwol | Chain Bomb Punch (finish)
- [ ] Blaster | Afterimage Shock
- [ ] Battle Mage | Union Aura
- [ ] Battle Mage | Union Aura Blow
- [ ] Battle Mage | Black Magic Alter
- [ ] Battle Mage | Grim Reaper
- [ ] Battle Mage | Abyssal Lightning (active)
- [ ] Mechanic | Mech Carrier
- [ ] Demon Avenger | Revenant
- [ ] Kaiser | Dragon Blaze
- [ ] Angelic Buster | Trinity Fusion
- [ ] Kinesis | Psychic Tornado
- [ ] Kinesis | Ultimate
- [ ] Kinesis | Ultimate
- [ ] Kinesis | Law of Gravity
- [ ] Adele | Ruin
- [ ] Adele | Infinite
- [ ] Adele | Restore
- [ ] Adele | Storm
- [ ] Illium | Crystal Gate
- [ ] Ark | Eternal Hungry Beast
- [ ] Hoyoung | Sage : Elemental Illusion

**Comment by Nougaga** [comment]
|job|skill|delay(6,data)|delay(2,measured)|applied?|
|---|---|---|---|---|
|Hero | Sword Illusion|870|660|O|
|Paladin | Mighty Mjolnir|840|630|O|
|Dark Knight | Beholder Impact|~~720~~|0|X|
|Dark Knight | Darkness Aura (start)|600|600|X|
|Dark Knight | Darkness Aura (finish)|570|**_480_**|O|
|Dark Knight | Gungnir's Descent+Darkness Aura (finish)|780+0|600+0|-|
|Fire/Poison | Fury of Ifrit|480|360|O|
|Fire/Poison | Poison Chain|780|600|O|
|Ice/Lightning | Jupiter Thunder|810|630|O|
|Crossbow Master | Repeating Crossbow Cartridge|660|510|O|
|Crossbow Master | Full Burst Shot|1080|810|O|
|Pathfinder | Relic Unbound|720|540|O|
|Night Lord | Throw Blasting|960|720|O|
|Viper | Howling Fist (finish)|2580|1950|O|
|Cannon | Pool Maker|960|**_750_**|O|
|Soul Master | Celestial Dance|570|570|X|
|Soul Master | Elysion|750|750|X|
|Soul Master | Soul Eclipse|810|630|O|
|Soul Master | Soluna Divide|990|750|O|
|Flame Wizard | Blazing Orbital Flame|210|180|O|
|Flame Wizard | Flame Discharge|840|840|X|
|Flame Wizard | Salamander Mischief|750|750|X|
|Wind Shooter | Vortex Sphere|960|720|O|
|Night Walker | Rapid Throw (finish)|630|480|O|
|Striker | Spear Lightning Continuity Attack|660|510|O|
|Striker | (cancel)|300|mostly 240|O|
|Striker | (finish)|660|510|O|
|Striker | (finish, cancel)|600|450|O|
|Mihile | Light of Courage|990|750|O|
|Mihile | Light of Courage (finish)|450|360|O|
|Aran | Blizzard Tempest|990|750|O|
|Luminous | Revelation Orb|900|690|O|
|Mercedes | Royal Knights|1680|1260|O|
|Phantom | Rift Break (move)|600|-|-|
|Phantom | Rift Break (no-move)|990|750|O|
|Eunwol | Chain Bomb Punch (finish)|1080|810|O|
|Blaster | Afterimage Shock|780|780|X|
|Battle Mage | Union Aura|810|810|X|
|Battle Mage | Union Aura Blow|810|630|O|
|Battle Mage | Black Magic Alter|690|690|X|
|Battle Mage | Grim Reaper|720|540|O|
|Battle Mage | Abyssal Lightning (active)|720|540|O|
|Mechanic | Mech Carrier|720|**_810_**|X|
|Demon Avenger | Revenant|1530|1530|X|
|Kaiser | Dragon Blaze|900|900|X|
|Angelic Buster | Trinity Fusion|870|660|O|
|Kinesis | Psychic Tornado|720|540|O|
|Kinesis | Psychic Tornado(throw)|720|540|O|
|Kinesis | Ultimate-Mind Over Matter|630|480|O|
|Kinesis | Ultimate-Psychic Shockwave|570|450|O|
|Kinesis | Law of Gravity|960|720|O|
|Adele | Ruin|780|600|O|
|Adele | Infinite|540|540|X|
|Adele | Restore|720|720|X|
|Adele | Storm|780|780|X|
|Illium | Crystal Gate|540|420|O|
|Ark | Eternal Hungry Beast |690|540|O|
|Hoyoung | Sage : Elemental Illusion|720|540|O|

note
- **bold**: longer than calculated one
My repeated measurements are showing the same results, so cross-check is needed.
  - Darkness Aura (finish)
  - Pool Maker
  - Mech Carrier
- ~~strikethrough~~: not related
  - Beholder Impact
- Rift Break (move): Between chained attacks, there are unfixed time when the character can move but cannot attack.

**Comment by Monolith11** [comment]
Thank you for test.
"longer than calculated" can be recording error, so I just applied as calculated delay.
If you sure "longer than calculated" skills always have longer delay, i'll apply that.
At least there's precedant. https://github.com/Monolith11/memo/wiki/Hoyoung-Skill-Mechanics

**Comment by Nougaga** [comment]
This is being edited until the table is completely filled.
Skills with some notes is likely to be inaccurate, so they'll be checked again.
