### ISSUE TITLE
Cadena issue

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#52]
Stroke1 + Wingdagger -> only first tick get final damage

Fury can hit 100%, but it does not summon each 0.6s. It summons after attack, so it can be delayed (like Adele - Creation)

Weapon Variety Finale is triggered from Weapon Variety III. so, it's use/min should be `=60/(ROUNDUP((J144/G194)/(60/N41), 0)*(60/N41))`, not `=60/(J144/G194)`.

**Comment by Monolith11** [comment]
weapon verity finale is stackable skill so current formula is ok.
other issues are fixed.
