### ISSUE TITLE
Zero assist skills issue

### ISSUE THREAD

**Issue by cheese98** [Monolith11/memo#54]
I have a question about assist skills while I am editing the DPM source code for Zero.

When tagging from Alpha to Beta, which character's stats are applied to Alpha's assist skills?

Some people say that the skills only follow their owner, regardless the active character; Alpha's skills are on Alpha, and Beta's skills are on Beta.

Others say that the skills are only depended on the current active character. They say that all skills are calculated under the active character's stats.

I tried to test with my Zero, making differences in critical rate, but it's not the exact method because it depends on probability.

May I ask you which one is right?

**Comment by Monolith11** [comment]
I tested in JMS
https://github.com/Monolith11/memo/wiki/Zero-Skill-Mechanics

**Comment by cheese98** [comment]
Thank you. So, does it mean that it's different in case by case?

**Comment by Monolith11** [comment]
Yes.
Also added assist delay section. It will very helpful.

**Comment by cheese98** [comment]
I didn't know about that, ty.

I need to know if Great sword mastery applies on Alpha's skills...  So I just put an inquiry into the Nexon customer service center. If the answer comes, I'll let you know.

**Comment by Monolith11** [comment]
I only tested crit rate and ignore defense tho...
Seems that problem is attack speed only.

**Comment by Monolith11** [comment]
Seems everything has been reflected to maplestats simulator so I'll close this issue.
