### ISSUE TITLE
Phantom 2nd job skill steal is missing

### ISSUE THREAD

**Issue by Monolith11** [Monolith11/memo#57]
Recover and investigate which skill is best.

- Rage
- Heal
- Steal

**Comment by icepeng** [comment]
I am currently using Rage.

Heal can be an option in real boss, Heal+Rift Break+Mark of Phantom combo.

but Heal's Final damage does not worth 600ms delay in DPM.

Steal and Rage have equal attack 30.

Steal has shorter delay then Rage, and have damage. But Rage can be used with pet skill.
