### ISSUE TITLE
Pathfinder F26, F35 is wrong

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#62]
Final damage is multiplied each stack

not `1+0.1*5`, `1.1^5` is right.

**Comment by icepeng** [comment]
also, target+1 by core enhancement does not apply to Cardinal Blast. Edge of Resonance need test.

**Comment by icepeng** [comment]
also, target+1 by core enhancement does not apply to Cardinal Blast

**Comment by Monolith11** [comment]
Cardinal Nlast is also multiplied by each stack.
Seems it benefits from target+1.

**Comment by Monolith11** [comment]
Cardinal Blast is also multiplied by each less target.
Also seems it benefits from target+1 core.
