### ISSUE TITLE
Conversion Starforce Changed

### ISSUE THREAD

**Issue by jj9810** [Monolith11/memo#84]
| Range | HP / star |
|-|-|
| 1~60 | 80 |
| 61~100 | 100 |
| 101~140 | 120 |
| 141~200 | 140 |
| 201~220 | 142 |
| 221~250 | 144 |
| 251~270 | 146 |
| 271~290 | 148 |
| 291~310 | 150 |
| 311~320 | 152 |
| 321~330 | 154 |
| 331~340 | 156 |
| 341~350 | 158 |
| 351~360 | 160 |
| 361~370 | 162 |
| 361~370 | 162 |
| 371~380 | 164 |
| 381~390 | 166 |

The last three values are expected values.

References:
http://www.inven.co.kr/board/maple/2294/153392
http://www.inven.co.kr/board/maple/2294/157806

**Comment by Monolith11** [comment]
moved to wiki
