### ISSUE TITLE
Dark Knight - Pierce Cyclone, Dark Spear hit

### ISSUE THREAD

**Issue by icepeng** [Monolith11/memo#9]
https://youtu.be/c0PDaF2kb7A

Pierce Cychone is hit is 300+15, sheet is 276+15
Dark Spear is 8\*7 per throw, sheet is 7\*7

In video, character throws Dark Spear 5 times, and use count is 40

**Comment by Monolith11** [comment]
and attack speed will apply to Dark Spear
all checked
